### ISSUE TITLE
Problem 632 is cooked

### ISSUE THREAD

**Issue by jwwells42** [denialromeo/3412-chess-problems#4]
Thank you for this work! I often include Polgar mates in my scholastic lessons, and when we're working digitally (or I'm on the projector), your website is my go-to. 

My students and I solved #632 with 1.Kb4, and then spent a long while trying to refute it since that wasn't an accepted answer. Once we ran out of legal moves to check, Stockfish verified that there are two solutions to this puzzle. Apologies if you've addressed cooked problems elsewhere, but I thought I'd save someone else some time if it hadn't been brought up yet.

**Comment by denialromeo** [comment]
Hi,

Thank you for playing! I'm thrilled that you're finding this app useful to share with others. It's very gratifying.

To go behind-the-scenes a bit, the app itself actually doesn't support multiple solutions. Basically, there's a file at https://raw.githubusercontent.com/denialromeo/4462-chess-problems/master/problems.json which contains problem starting positions and accompanying moves to solve. The app checks the player's move against the associated move-set, and if they don't match, it rejects the move.

Because there's often multiple ways to deliver checkmate on the final move, the app allows any final move which leaves the board position in checkmate, but yes, "cooked" solutions like the alternative one you and your students noted are a hole. If a move before the final move is possibly valid but doesn't match what's expected, it would be rejected.

Getting around this would probably require me to run all starting positions through Stockfish to get all possible solutions, then encode them in the JSON file, then update the front-end to check against each possible solution. This could wind up taking a long while to implement for possibly limited benefit.
